[supervisord]
nodaemon=true

[inet_http_server]
port=0.0.0.0:9991
username=admin
password=123

[program:kea]
command=/usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4.conf
directory=/etc/kea

autostart=true
autorestart=true

stdout_logfile=/tmp/kea-stdout.log
stderr_logfile=/tmp/kea-stderr.log
