FROM alpine:latest 

RUN apk update; apk upgrade; apk add bash busybox iputils-ping arping nano \
supervisor kea;\
mkdir -p /var/lib/kea /run/kea ; chmod 750 /var/lib/kea /run/kea

COPY ./supervisord.conf /etc/supervisor/supervisor.conf
COPY ./kea.yaml /etc/kea/kea-dhcp4.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisor.conf"]